# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fcnn.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fcnn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfcnn.proto\x12\x04\x66\x63nn\"%\n\x13NetworkArchitecture\x12\x0e\n\x06layers\x18\x01 \x03(\x05\"p\n\tFCNNModel\x12\x33\n\rlayer_weights\x18\x01 \x03(\x0b\x32\x1c.fcnn.FCNNModel.LayerWeights\x1a.\n\x0cLayerWeights\x12\x0f\n\x07weights\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\x03\x32\x43\n\x04\x46\x43NN\x12;\n\x0b\x63reateModel\x12\x19.fcnn.NetworkArchitecture\x1a\x0f.fcnn.FCNNModel\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fcnn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKARCHITECTURE']._serialized_start=20
  _globals['_NETWORKARCHITECTURE']._serialized_end=57
  _globals['_FCNNMODEL']._serialized_start=59
  _globals['_FCNNMODEL']._serialized_end=171
  _globals['_FCNNMODEL_LAYERWEIGHTS']._serialized_start=125
  _globals['_FCNNMODEL_LAYERWEIGHTS']._serialized_end=171
  _globals['_FCNN']._serialized_start=173
  _globals['_FCNN']._serialized_end=240
# @@protoc_insertion_point(module_scope)
