/**
 * @fileoverview gRPC-Web generated client stub for fcnn
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: fcnn.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.fcnn = require('./fcnn_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.fcnn.FCNNClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.fcnn.FCNNPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.fcnn.NetworkArchitecture,
 *   !proto.fcnn.FCNNModel>}
 */
const methodDescriptor_FCNN_createModel = new grpc.web.MethodDescriptor(
  '/fcnn.FCNN/createModel',
  grpc.web.MethodType.UNARY,
  proto.fcnn.NetworkArchitecture,
  proto.fcnn.FCNNModel,
  /**
   * @param {!proto.fcnn.NetworkArchitecture} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.fcnn.FCNNModel.deserializeBinary
);


/**
 * @param {!proto.fcnn.NetworkArchitecture} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.fcnn.FCNNModel)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.fcnn.FCNNModel>|undefined}
 *     The XHR Node Readable Stream
 */
proto.fcnn.FCNNClient.prototype.createModel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/fcnn.FCNN/createModel',
      request,
      metadata || {},
      methodDescriptor_FCNN_createModel,
      callback);
};


/**
 * @param {!proto.fcnn.NetworkArchitecture} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.fcnn.FCNNModel>}
 *     Promise that resolves to the response
 */
proto.fcnn.FCNNPromiseClient.prototype.createModel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/fcnn.FCNN/createModel',
      request,
      metadata || {},
      methodDescriptor_FCNN_createModel);
};


module.exports = proto.fcnn;

