// source: fcnn.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.fcnn.FCNNModel', null, global);
goog.exportSymbol('proto.fcnn.FCNNModel.LayerWeights', null, global);
goog.exportSymbol('proto.fcnn.NetworkArchitecture', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fcnn.NetworkArchitecture = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fcnn.NetworkArchitecture.repeatedFields_, null);
};
goog.inherits(proto.fcnn.NetworkArchitecture, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fcnn.NetworkArchitecture.displayName = 'proto.fcnn.NetworkArchitecture';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fcnn.FCNNModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fcnn.FCNNModel.repeatedFields_, null);
};
goog.inherits(proto.fcnn.FCNNModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fcnn.FCNNModel.displayName = 'proto.fcnn.FCNNModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fcnn.FCNNModel.LayerWeights = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fcnn.FCNNModel.LayerWeights.repeatedFields_, null);
};
goog.inherits(proto.fcnn.FCNNModel.LayerWeights, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fcnn.FCNNModel.LayerWeights.displayName = 'proto.fcnn.FCNNModel.LayerWeights';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fcnn.NetworkArchitecture.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fcnn.NetworkArchitecture.prototype.toObject = function(opt_includeInstance) {
  return proto.fcnn.NetworkArchitecture.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fcnn.NetworkArchitecture} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fcnn.NetworkArchitecture.toObject = function(includeInstance, msg) {
  var f, obj = {
layersList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fcnn.NetworkArchitecture}
 */
proto.fcnn.NetworkArchitecture.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fcnn.NetworkArchitecture;
  return proto.fcnn.NetworkArchitecture.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fcnn.NetworkArchitecture} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fcnn.NetworkArchitecture}
 */
proto.fcnn.NetworkArchitecture.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLayers(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fcnn.NetworkArchitecture.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fcnn.NetworkArchitecture.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fcnn.NetworkArchitecture} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fcnn.NetworkArchitecture.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLayersList();
  if (f.length > 0) {
    writer.writePackedInt32(
      1,
      f
    );
  }
};


/**
 * repeated int32 layers = 1;
 * @return {!Array<number>}
 */
proto.fcnn.NetworkArchitecture.prototype.getLayersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.fcnn.NetworkArchitecture} returns this
 */
proto.fcnn.NetworkArchitecture.prototype.setLayersList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.fcnn.NetworkArchitecture} returns this
 */
proto.fcnn.NetworkArchitecture.prototype.addLayers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fcnn.NetworkArchitecture} returns this
 */
proto.fcnn.NetworkArchitecture.prototype.clearLayersList = function() {
  return this.setLayersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fcnn.FCNNModel.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fcnn.FCNNModel.prototype.toObject = function(opt_includeInstance) {
  return proto.fcnn.FCNNModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fcnn.FCNNModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fcnn.FCNNModel.toObject = function(includeInstance, msg) {
  var f, obj = {
layerWeightsList: jspb.Message.toObjectList(msg.getLayerWeightsList(),
    proto.fcnn.FCNNModel.LayerWeights.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fcnn.FCNNModel}
 */
proto.fcnn.FCNNModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fcnn.FCNNModel;
  return proto.fcnn.FCNNModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fcnn.FCNNModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fcnn.FCNNModel}
 */
proto.fcnn.FCNNModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fcnn.FCNNModel.LayerWeights;
      reader.readMessage(value,proto.fcnn.FCNNModel.LayerWeights.deserializeBinaryFromReader);
      msg.addLayerWeights(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fcnn.FCNNModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fcnn.FCNNModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fcnn.FCNNModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fcnn.FCNNModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLayerWeightsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.fcnn.FCNNModel.LayerWeights.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fcnn.FCNNModel.LayerWeights.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.toObject = function(opt_includeInstance) {
  return proto.fcnn.FCNNModel.LayerWeights.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fcnn.FCNNModel.LayerWeights} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fcnn.FCNNModel.LayerWeights.toObject = function(includeInstance, msg) {
  var f, obj = {
weightsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
shapeList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fcnn.FCNNModel.LayerWeights}
 */
proto.fcnn.FCNNModel.LayerWeights.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fcnn.FCNNModel.LayerWeights;
  return proto.fcnn.FCNNModel.LayerWeights.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fcnn.FCNNModel.LayerWeights} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fcnn.FCNNModel.LayerWeights}
 */
proto.fcnn.FCNNModel.LayerWeights.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addWeights(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addShape(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fcnn.FCNNModel.LayerWeights.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fcnn.FCNNModel.LayerWeights} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fcnn.FCNNModel.LayerWeights.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWeightsList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
  f = message.getShapeList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
};


/**
 * repeated double weights = 1;
 * @return {!Array<number>}
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.getWeightsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.fcnn.FCNNModel.LayerWeights} returns this
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.setWeightsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.fcnn.FCNNModel.LayerWeights} returns this
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.addWeights = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fcnn.FCNNModel.LayerWeights} returns this
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.clearWeightsList = function() {
  return this.setWeightsList([]);
};


/**
 * repeated int64 shape = 2;
 * @return {!Array<number>}
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.getShapeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.fcnn.FCNNModel.LayerWeights} returns this
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.setShapeList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.fcnn.FCNNModel.LayerWeights} returns this
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.addShape = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fcnn.FCNNModel.LayerWeights} returns this
 */
proto.fcnn.FCNNModel.LayerWeights.prototype.clearShapeList = function() {
  return this.setShapeList([]);
};


/**
 * repeated LayerWeights layer_weights = 1;
 * @return {!Array<!proto.fcnn.FCNNModel.LayerWeights>}
 */
proto.fcnn.FCNNModel.prototype.getLayerWeightsList = function() {
  return /** @type{!Array<!proto.fcnn.FCNNModel.LayerWeights>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.fcnn.FCNNModel.LayerWeights, 1));
};


/**
 * @param {!Array<!proto.fcnn.FCNNModel.LayerWeights>} value
 * @return {!proto.fcnn.FCNNModel} returns this
*/
proto.fcnn.FCNNModel.prototype.setLayerWeightsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.fcnn.FCNNModel.LayerWeights=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fcnn.FCNNModel.LayerWeights}
 */
proto.fcnn.FCNNModel.prototype.addLayerWeights = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.fcnn.FCNNModel.LayerWeights, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fcnn.FCNNModel} returns this
 */
proto.fcnn.FCNNModel.prototype.clearLayerWeightsList = function() {
  return this.setLayerWeightsList([]);
};


goog.object.extend(exports, proto.fcnn);
